services:
  web:
    build:
      context: .
      args:
        - MONGODB_URI=mongodb://admin:${MONGODB_PASSWORD}@db:27017/dailyreport?authSource=admin
    ports:
      - "3016:3016"  # Application port
    environment:
      - PORT=3016
      - MONGODB_URI=mongodb://admin:${MONGODB_PASSWORD}@db:27017/dailyreport?authSource=admin
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache
      - /var/tmp

  db:
    image: mongo:7.0  # Use specific version for security
    ports:
      - "27018:27017"  # Use different external port to avoid conflicts
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=dailyreport
    volumes:
      - mongo-data:/data/db
      - ./backups:/data/backup
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./logs:/var/log/mongodb
    networks:
      - app-network
    command: >
      mongod 
      --auth 
      --bind_ip_all
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    ulimits:
      nproc: 65536
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Add monitoring service
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"  # MongoDB Express port
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://admin:${MONGODB_PASSWORD}@db:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mongodb

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1